### ISSUE TITLE
Support for YAML

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#101]
After using Kubernetes for a while I have to say that I find YAML declarations a lot nicer than JSON.

Are you planning on supporting this?

**Comment by tomkerkhove** [comment]
Circling back to this - In #134 @VipulM-MSFT mentioned CLI support for YAML is coming. I presume this will mean that the above scenario will be supported and I can deploy my YAML templates via `az mesh deployment create`?

**Comment by VipulM-MSFT** [comment]
Yes that is the idea.

**Comment by mattquinn** [comment]
>           Yes that is the idea.

My understanding is that this is now part of the CLI toolkit using the --input-yaml-files parameter.

Is that correct? Is it still a work in progress?

I'm using Azure CLI 2.0.52 service fabric mesh installed, but am getting lots of parsing errors from really basic YAML files. They work with the Visual Studio SDK to publish to Azure, but point the az mesh deployment create command at them and there's all manner of issues.

I have a really empty app.yaml: 

`application:
  schemaVersion: 1.0.0-preview2
  name: MQSFMesh101`

And then a couple of services within the solution that have service.yaml files as below:

`application:
  schemaVersion: 1.0.0-preview2
  name: MQSFMesh101
  properties:
    services:
      - name: WebFrontEnd
        properties:
          description: WebFrontEnd description.
          osType: Windows
          codePackages:
            - name: WebFrontEnd
              image: webfrontend:dev
              endpoints:
                - name: WebFrontEndListener
                  port: 20005
              environmentVariables:
                - name: ASPNETCORE_URLS
                  value: http://+:20005
                - name: MQSFMesh101_BackendServiceHostName
                  value: backendservice
                - name: MQSFMesh101_BackendServicePort
                  value: 20006
              resources:
                requests:
                  cpu: "[parameters('WebFrontEnd_cpu')]"
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: MQSFMesh101Network
              endpointRefs:
                - name: WebFrontEndListener`


As I say, the Visual Studio tooling takes these and publishes without issue. 

Run a command such as:

`az mesh deployment create --resource-group RG_ServiceFabricMeshDec12Demo --input-yaml-files .\app.yaml,.\gateway.yaml,.\network.yaml,'..\..\BackendService\Service Resources\service.yaml','..\..\WebFrontApp\Service Resources\service.yaml' --parameters ..\Environments\Cloud\parameters.yaml`

from the relevant path and it throws all manger of syntax errors when trying to parse the yaml (all files have been yamllint'd to verify they're valid YAML.


`'list' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\commands\__init__.py", line 346, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\commands\__init__.py", line 320, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\commands\__init__.py", line 169, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\__init__.py", line 440, in default_command_handler
  File "C:\Users\***\.azure\cliextensions\mesh\azext_mesh\custom.py", line 283, in deploy_arm_template
    input_yaml_files, deployment_name, parameters, mode, no_wait=no_wait)
  File "C:\Users\***\.azure\cliextensions\mesh\azext_mesh\custom.py", line 249, in _deploy_arm_template_core
    SFMergeUtility.sf_merge_utility(file_path_list, "SF_SBZ_RP_JSON", parameters=parameters, output_dir=None, prefix=prefix)
  File "C:\Users\***\.azure\cliextensions\mesh\sfmergeutility\sf_merge_utility.py", line 48, in sf_merge_utility
    merged_resource_documents = SFMergeUtility.load_and_merge_partial_documents(input_list)
  File "C:\Users\***\.azure\cliextensions\mesh\sfmergeutility\sf_merge_utility.py", line 207, in load_and_merge_partial_documents
    name = my_dict.get(kind).get(Constants.PrimaryPropertyName)
AttributeError: 'list' object has no attribute 'get'`





Am I missing something here? I cannot find any documentation on what elements should/must exist in the YAML file to make the deployment work - or am I totally misinterpreting what the --input-yaml-files parameter is for?

My understanding is you can use this to have it generate the ARM template JSON so you have only to maintain once definition of your services in YAML, rather than YAML for Docker/SFMesh and an ARM replica for deployment to Azure. Am I reading that right?
[yaml-files.zip](https://github.com/Azure/service-fabric-mesh-preview/files/2683509/yaml-files.zip)

**Comment by anantshankar17** [comment]
Hi @mattquinn 
I looked at your yamls, and it seems the app.yaml and the service-frontend.yaml have 2 stay characters at  the beginning. Removing those by changing the file encoding to UTF-8 (without BOM), the same deployment command works for me. 
Refer to this https://stackoverflow.com/questions/3255993/how-do-i-remove-%C3%AF-from-the-beginning-of-a-file. Can you also give that a try and let us know ?

**Comment by mattquinn** [comment]
Thank you @anantshankar17 - life saver. I even looked at the encoding having seen the strange representation of whitespace chars in the error message, but somehow managed to think I'd looked at / fixed that. 

You were indeed right - Save without encoding / UTF-8 Codepage 65001 and BOOM! works like a charm.

**Comment by anantshankar17** [comment]
@mattquinn good to know. Closing this thread.
