### ISSUE TITLE
Visual Studio Tools for Service Fabric Mesh - Support for multiple code-packages

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#238]
Currently the `service.yaml` is stored in a specific project which means that **one service** can only have **one code-package**.

Will this change in the future?

**Comment by VipulM-MSFT** [comment]
@dbreshears for the timeline and priority. 

@tomkerkhove - there is an supported workaround that works today. 
- Create a new project 
- Change the name of the service in the YAML file for the new project to be the same as the previous service
- Since our tool does structural merge, they will end up as two separate code packages in the same service (they will NOT be part of the same POD/namespace for Windows)

**Comment by dbreshears** [comment]
I've added a backlog item for us to investigate a solution to this in the tooling.   No timeline at the moment

**Comment by aloneguid** [comment]
How does multiple code packages work in the same service? It's a bit unclear whether they will run two separate containers, or do some magic like Kubernetes pods?

**Comment by mattrowmsft** [comment]
They act like pods.  FYI this item is to track the VS experience building these, it is already possible to do this if you create your own templates.
