### ISSUE TITLE
Can an sf application be forcefully overwritten?

### ISSUE THREAD

**Issue by damienestewart** [Azure/service-fabric-mesh-preview#330]
It seems that an sfmesh application is only redeployed when there are changes to the settings, which makes complete sense. In my case, I made code changes and rebuilt my docker image with the same exact name and tag. When I tried to redeploy, expecting the sf app to be updated, it wasn't. I suspect that it's because the settings didn't change due to using the same image name/tag.

Is this intended behavior? Is it mandatory to change the docker image tag for a scenario like this, or is there a way to force the redeployment?

**Comment by guibirow** [comment]
The correct way is updating the tags on every change, maybe use the build number as tag, because you did use the same tag, the engine used the cached version already in the host. This is one of the reasons you should not use latest or omit the tags when deploying a container.

I don't think there is a "force" update option. Right now we can't even restart the container :(

**Comment by damienestewart** [comment]
I see, thanks for the awesome input @guibirow!

**Comment by raunakpandya** [comment]
Hope the answer clarifies. Closing the issue..
